version: "3.9"

services:
  web:
    build: .
    container_name: jo4dev_onboard
    restart: always
    env_file: .env
    volumes:
      - ./instance:/app/instance
      - ./credentials:/app/credentials
      - ./static/uploads:/app/static/uploads
    networks:
      - tunnel-net

networks:
  tunnel-net:
    external: true
