from datetime import datetime

from flask_sqlalchemy import SQLAlchemy


db = SQLAlchemy()


class Submission(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    submission_id = db.Column(db.String(36), unique=True, nullable=False, index=True)
    company_name = db.Column(db.String(180), nullable=False)
    industry = db.Column(db.String(80))
    contact_name = db.Column(db.String(140), nullable=False)
    job_title = db.Column(db.String(140))
    contact_email = db.Column(db.String(180), nullable=False)
    phone = db.Column(db.String(60))
    address = db.Column(db.Text)
    existing_url = db.Column(db.String(250))
    referral_source = db.Column(db.String(80))
    services = db.Column(db.JSON, default=list)
    main_goal = db.Column(db.Text)
    target_audience = db.Column(db.Text)
    competitors = db.Column(db.Text)
    likes_competitors = db.Column(db.Text)
    dislikes_competitors = db.Column(db.Text)
    has_content = db.Column(db.String(40))
    page_count = db.Column(db.String(40))
    pages_needed = db.Column(db.JSON, default=list)
    needs_blog = db.Column(db.String(40))
    sells_online = db.Column(db.String(40))
    product_count = db.Column(db.Integer)
    languages = db.Column(db.JSON, default=list)
    multilingual = db.Column(db.String(40))
    seo_history = db.Column(db.String(80))
    paid_ads = db.Column(db.String(80))
    target_keywords = db.Column(db.Text)
    google_business = db.Column(db.String(80))
    analytics_setup = db.Column(db.String(80))
    social_platforms = db.Column(db.JSON, default=list)
    launch_date = db.Column(db.String(40))
    deadline_urgency = db.Column(db.String(40))
    budget = db.Column(db.String(80))
    payment_preference = db.Column(db.String(80))
    maintenance_budget = db.Column(db.String(40))
    involvement_level = db.Column(db.String(120))
    main_contact_name = db.Column(db.String(140))
    main_contact_email = db.Column(db.String(180))
    integrations = db.Column(db.Text)
    other_notes = db.Column(db.Text)
    digital_presence_rating = db.Column(db.Integer)
    primary_colour = db.Column(db.String(20))
    secondary_colour = db.Column(db.String(20))
    font_preferences = db.Column(db.String(250))
    logo_filename = db.Column(db.String(250))
    logo_drive_url = db.Column(db.String(500))
    photo_filenames = db.Column(db.JSON, default=list)
    reference_filenames = db.Column(db.JSON, default=list)
    gdrive_folder_id = db.Column(db.String(180))
    gdrive_folder_url = db.Column(db.String(500))
    gdoc_id = db.Column(db.String(180))
    gdoc_url = db.Column(db.String(500))
    status = db.Column(db.String(40), default="new", nullable=False)
    priority = db.Column(db.String(40), default="normal")
    deal_value = db.Column(db.String(80))
    next_follow_up = db.Column(db.String(10))
    last_contacted = db.Column(db.String(10))
    seo_package = db.Column(db.String(40), default="basic")
    agile_methodology = db.Column(db.String(40), default="scrum")
    sprint_name = db.Column(db.String(120))
    sprint_goal = db.Column(db.Text)
    sprint_start = db.Column(db.String(10))
    sprint_end = db.Column(db.String(10))
    project_owner = db.Column(db.String(140))
    sprint_cadence = db.Column(db.String(80), default="weekly")
    admin_notes = db.Column(db.Text)
    submitted_at = db.Column(db.DateTime, default=datetime.utcnow, nullable=False)
    updated_at = db.Column(db.DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    seo_items = db.relationship("SEOAuditItem", backref="submission", cascade="all, delete-orphan")
    tasks = db.relationship("Task", backref="submission", cascade="all, delete-orphan")


class SEOAuditItem(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    submission_id = db.Column(db.Integer, db.ForeignKey("submission.id"), nullable=False)
    category = db.Column(db.String(80), nullable=False)
    item_key = db.Column(db.String(180), nullable=False)
    label = db.Column(db.String(240), nullable=False)
    package = db.Column(db.String(40), default="basic")
    is_complete = db.Column(db.Boolean, default=False)
    updated_at = db.Column(db.DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)


class Task(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    submission_id = db.Column(db.Integer, db.ForeignKey("submission.id"), nullable=False)
    title = db.Column(db.String(220), nullable=False)
    description = db.Column(db.Text)
    tag = db.Column(db.String(40), default="Dev")
    agile_type = db.Column(db.String(40), default="task")
    sprint = db.Column(db.String(120))
    estimate_hours = db.Column(db.String(20))
    acceptance_criteria = db.Column(db.Text)
    blocker = db.Column(db.Text)
    priority = db.Column(db.String(40), default="normal")
    due_date = db.Column(db.String(10))
    reminder_date = db.Column(db.String(10))
    reminder_note = db.Column(db.String(220))
    column = db.Column(db.Integer, default=0)
    created_at = db.Column(db.DateTime, default=datetime.utcnow, nullable=False)
